# MAKEFILE ITY proj2
# 
# Autor: Dominik Křivohlávek
# 1BIT

all:
	latex proj2.tex
	latex proj2.tex # Druhy preklad pro reference
	dvips -t a4 proj2.dvi
	ps2pdf proj2.ps

clean:
	rm *.aux *.dvi *.pdf *log *ps